/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.SaveVehicle;
import Model.Vehicle;
import javax.swing.JFileChooser;

/**
 *
 * @author Bawantha
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JPanel();
        optionIcons = new javax.swing.JPanel();
        buttonClose = new javax.swing.JPanel();
        btnClose = new javax.swing.JLabel();
        menu = new javax.swing.JPanel();
        meunIcons = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        menuSlide = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnViewV = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnHome = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnAddV = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnSearchV = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btnBookV = new javax.swing.JLabel();
        dash = new javax.swing.JPanel();
        dashTabPanel = new javax.swing.JTabbedPane();
        tabHome = new javax.swing.JPanel();
        tabViewVehicle = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        tabAddVehicle = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtLplate = new javax.swing.JTextField();
        cmbMake = new javax.swing.JComboBox<>();
        cmbYear = new javax.swing.JComboBox<>();
        txtModel = new javax.swing.JTextField();
        cmbCategory = new javax.swing.JComboBox<>();
        txtCostpm = new javax.swing.JTextField();
        imgVehicle = new javax.swing.JLabel();
        btnBrowse = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        tabSearchVehicle = new javax.swing.JPanel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox<>();
        jComboBox6 = new javax.swing.JComboBox<>();
        jTextField6 = new javax.swing.JTextField();
        jComboBox7 = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        tabBookVehicle = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jComboBox8 = new javax.swing.JComboBox<>();
        jTextField5 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1200, 800));

        header.setBackground(new java.awt.Color(23, 35, 76));
        header.setPreferredSize(new java.awt.Dimension(900, 64));
        header.setRequestFocusEnabled(false);
        header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        optionIcons.setPreferredSize(new java.awt.Dimension(150, 50));

        buttonClose.setBackground(new java.awt.Color(23, 35, 76));
        buttonClose.setToolTipText("");
        buttonClose.setLayout(new java.awt.BorderLayout());

        btnClose.setBackground(new java.awt.Color(0, 106, 188));
        btnClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnClose.setIcon(new javax.swing.ImageIcon("E:\\Downloads\\icons8-cancel-64.png")); // NOI18N
        btnClose.setToolTipText("");
        buttonClose.add(btnClose, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout optionIconsLayout = new javax.swing.GroupLayout(optionIcons);
        optionIcons.setLayout(optionIconsLayout);
        optionIconsLayout.setHorizontalGroup(
            optionIconsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 64, Short.MAX_VALUE)
            .addGroup(optionIconsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(optionIconsLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(buttonClose, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        optionIconsLayout.setVerticalGroup(
            optionIconsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 64, Short.MAX_VALUE)
            .addGroup(optionIconsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(optionIconsLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(buttonClose, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        header.add(optionIcons, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 0, 64, 64));

        getContentPane().add(header, java.awt.BorderLayout.PAGE_START);

        menu.setBackground(new java.awt.Color(65, 76, 80));
        menu.setPreferredSize(new java.awt.Dimension(270, 505));
        menu.setLayout(new java.awt.BorderLayout());

        meunIcons.setBackground(new java.awt.Color(23, 35, 76));
        meunIcons.setPreferredSize(new java.awt.Dimension(64, 625));
        meunIcons.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(23, 35, 76));
        jPanel6.setLayout(new java.awt.BorderLayout());

        jLabel30.setIcon(new javax.swing.ImageIcon("E:\\Downloads\\icons8-transaction-list-64.png")); // NOI18N
        jPanel6.add(jLabel30, java.awt.BorderLayout.CENTER);

        meunIcons.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 256, 64, 64));

        jPanel7.setBackground(new java.awt.Color(23, 35, 76));
        jPanel7.setForeground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new java.awt.BorderLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon("E:\\Downloads\\icons8-home-64.png")); // NOI18N
        jLabel6.setToolTipText("");
        jPanel7.add(jLabel6, java.awt.BorderLayout.CENTER);

        meunIcons.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 64, 64));

        jPanel8.setBackground(new java.awt.Color(23, 35, 76));
        jPanel8.setLayout(new java.awt.BorderLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon("E:\\Downloads\\icons8-car-rental-64.png")); // NOI18N
        jPanel8.add(jLabel7, java.awt.BorderLayout.CENTER);

        meunIcons.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 64, 64, 64));

        jPanel9.setBackground(new java.awt.Color(23, 35, 76));
        jPanel9.setLayout(new java.awt.BorderLayout());

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon("E:\\Downloads\\icons8-add-40.png")); // NOI18N
        jLabel8.setToolTipText("");
        jPanel9.add(jLabel8, java.awt.BorderLayout.CENTER);

        meunIcons.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 128, 64, 64));

        jPanel10.setBackground(new java.awt.Color(23, 35, 76));
        jPanel10.setLayout(new java.awt.BorderLayout());

        jLabel9.setIcon(new javax.swing.ImageIcon("E:\\Downloads\\icons8-search-64.png")); // NOI18N
        jLabel9.setToolTipText("");
        jPanel10.add(jLabel9, java.awt.BorderLayout.CENTER);

        meunIcons.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 192, 64, 64));

        menu.add(meunIcons, java.awt.BorderLayout.LINE_START);

        menuSlide.setBackground(new java.awt.Color(0, 48, 131));
        menuSlide.setForeground(new java.awt.Color(2, 127, 255));
        menuSlide.setToolTipText("");
        menuSlide.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 48, 131));
        jPanel1.setLayout(new java.awt.BorderLayout());

        btnViewV.setBackground(new java.awt.Color(2, 127, 255));
        btnViewV.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        btnViewV.setForeground(new java.awt.Color(255, 255, 255));
        btnViewV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnViewV.setText("VIEW VEHICLE");
        btnViewV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnViewVMouseClicked(evt);
            }
        });
        jPanel1.add(btnViewV, java.awt.BorderLayout.CENTER);

        menuSlide.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 64, 205, 64));

        jPanel2.setBackground(new java.awt.Color(0, 48, 131));
        jPanel2.setLayout(new java.awt.BorderLayout());

        btnHome.setBackground(new java.awt.Color(2, 127, 255));
        btnHome.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        btnHome.setForeground(new java.awt.Color(255, 255, 255));
        btnHome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnHome.setText("HOME");
        btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHomeMouseClicked(evt);
            }
        });
        jPanel2.add(btnHome, java.awt.BorderLayout.CENTER);

        menuSlide.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 205, 64));

        jPanel3.setBackground(new java.awt.Color(0, 48, 131));
        jPanel3.setLayout(new java.awt.BorderLayout());

        btnAddV.setBackground(new java.awt.Color(2, 127, 255));
        btnAddV.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        btnAddV.setForeground(new java.awt.Color(255, 255, 255));
        btnAddV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAddV.setText("ADD VEHICLE");
        btnAddV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddVMouseClicked(evt);
            }
        });
        jPanel3.add(btnAddV, java.awt.BorderLayout.CENTER);

        menuSlide.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 128, 220, 64));

        jPanel4.setBackground(new java.awt.Color(0, 48, 131));
        jPanel4.setLayout(new java.awt.BorderLayout());

        btnSearchV.setBackground(new java.awt.Color(2, 127, 255));
        btnSearchV.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        btnSearchV.setForeground(new java.awt.Color(255, 255, 255));
        btnSearchV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSearchV.setText("SEARCH VEHICLE");
        btnSearchV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSearchVMouseClicked(evt);
            }
        });
        jPanel4.add(btnSearchV, java.awt.BorderLayout.CENTER);

        menuSlide.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 192, 205, 64));

        jPanel5.setBackground(new java.awt.Color(0, 48, 131));
        jPanel5.setLayout(new java.awt.BorderLayout());

        btnBookV.setBackground(new java.awt.Color(0, 48, 131));
        btnBookV.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        btnBookV.setForeground(new java.awt.Color(255, 255, 255));
        btnBookV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnBookV.setText("BOOK VEHICLE");
        btnBookV.setToolTipText("");
        btnBookV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBookVMouseClicked(evt);
            }
        });
        jPanel5.add(btnBookV, java.awt.BorderLayout.CENTER);

        menuSlide.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 256, 205, 64));

        menu.add(menuSlide, java.awt.BorderLayout.CENTER);

        getContentPane().add(menu, java.awt.BorderLayout.LINE_START);

        dash.setBackground(new java.awt.Color(255, 255, 255));
        dash.setLayout(new java.awt.BorderLayout());

        dashTabPanel.setBackground(new java.awt.Color(255, 255, 255));
        dashTabPanel.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N

        tabHome.setBackground(new java.awt.Color(255, 255, 255));
        tabHome.setToolTipText("");
        tabHome.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        tabHome.setInheritsPopupMenu(true);

        javax.swing.GroupLayout tabHomeLayout = new javax.swing.GroupLayout(tabHome);
        tabHome.setLayout(tabHomeLayout);
        tabHomeLayout.setHorizontalGroup(
            tabHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 943, Short.MAX_VALUE)
        );
        tabHomeLayout.setVerticalGroup(
            tabHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 904, Short.MAX_VALUE)
        );

        dashTabPanel.addTab("HOME", tabHome);

        tabViewVehicle.setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jButton1.setText("VIEW ALL");

        jTable1.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout tabViewVehicleLayout = new javax.swing.GroupLayout(tabViewVehicle);
        tabViewVehicle.setLayout(tabViewVehicleLayout);
        tabViewVehicleLayout.setHorizontalGroup(
            tabViewVehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabViewVehicleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabViewVehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(tabViewVehicleLayout.createSequentialGroup()
                        .addGap(0, 799, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addGap(29, 29, 29))
        );
        tabViewVehicleLayout.setVerticalGroup(
            tabViewVehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabViewVehicleLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(228, Short.MAX_VALUE))
        );

        dashTabPanel.addTab("VIEW", tabViewVehicle);

        tabAddVehicle.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 36, 115));
        jLabel1.setText("License Plate");

        jLabel2.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 36, 115));
        jLabel2.setText("Year");

        jLabel3.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 36, 115));
        jLabel3.setText("Make");

        jLabel4.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 36, 115));
        jLabel4.setText("Model");

        jLabel5.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 36, 115));
        jLabel5.setText("Category");

        jLabel11.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 36, 115));
        jLabel11.setText("Cost per Month");

        txtLplate.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N

        cmbMake.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        cmbMake.setForeground(new java.awt.Color(0, 36, 115));
        cmbMake.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Make--" }));

        cmbYear.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        cmbYear.setForeground(new java.awt.Color(0, 36, 115));
        cmbYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Year--", "2024", "2023", "2022", "2021", "2020", "2019", "2018", "2017", "2016", "2015", "2014", "2013", "2012", "2011", "2010", "2009", "2008", "2007", "2006", "2005", "2004", "2003", "2002", "2001", "2000", "1999", "1998", "1997", "1996", "1995", "1994", "1993", "1992", "1991", "1990" }));
        cmbYear.setToolTipText("");

        txtModel.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        txtModel.setToolTipText("");

        cmbCategory.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        cmbCategory.setForeground(new java.awt.Color(0, 36, 115));
        cmbCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Category--" }));

        txtCostpm.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        txtCostpm.setToolTipText("");

        imgVehicle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgVehicle.setText("Photo");
        imgVehicle.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnBrowse.setBackground(new java.awt.Color(0, 106, 188));
        btnBrowse.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        btnBrowse.setForeground(new java.awt.Color(255, 255, 255));
        btnBrowse.setText("Browse");
        btnBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseActionPerformed(evt);
            }
        });

        btnSave.setBackground(new java.awt.Color(0, 106, 188));
        btnSave.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnClear.setBackground(new java.awt.Color(0, 106, 188));
        btnClear.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        btnClear.setForeground(new java.awt.Color(255, 255, 255));
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tabAddVehicleLayout = new javax.swing.GroupLayout(tabAddVehicle);
        tabAddVehicle.setLayout(tabAddVehicleLayout);
        tabAddVehicleLayout.setHorizontalGroup(
            tabAddVehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabAddVehicleLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(tabAddVehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabAddVehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(jLabel5)
                    .addComponent(jLabel11))
                .addGap(55, 55, 55)
                .addGroup(tabAddVehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCostpm)
                    .addComponent(txtLplate)
                    .addComponent(cmbYear, 0, 158, Short.MAX_VALUE)
                    .addComponent(cmbMake, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtModel)
                    .addComponent(cmbCategory, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(imgVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addGroup(tabAddVehicleLayout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(btnSave)
                .addGap(58, 58, 58)
                .addComponent(btnClear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 356, Short.MAX_VALUE)
                .addComponent(btnBrowse)
                .addGap(160, 160, 160))
        );
        tabAddVehicleLayout.setVerticalGroup(
            tabAddVehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabAddVehicleLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(tabAddVehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(tabAddVehicleLayout.createSequentialGroup()
                        .addGroup(tabAddVehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtLplate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(tabAddVehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cmbYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(tabAddVehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cmbMake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(tabAddVehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(tabAddVehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cmbCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(tabAddVehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCostpm)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(imgVehicle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(68, 68, 68)
                .addGroup(tabAddVehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClear)
                    .addComponent(btnSave)
                    .addComponent(btnBrowse))
                .addContainerGap(409, Short.MAX_VALUE))
        );

        dashTabPanel.addTab("ADD", tabAddVehicle);

        tabSearchVehicle.setBackground(new java.awt.Color(255, 255, 255));

        jComboBox4.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel13.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 36, 115));
        jLabel13.setText("Make");

        jTextField4.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jTextField4.setToolTipText("");

        jLabel14.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 36, 115));
        jLabel14.setText("Model");

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Photo");
        jLabel15.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel16.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 36, 115));
        jLabel16.setText("Category");

        jButton3.setBackground(new java.awt.Color(0, 106, 188));
        jButton3.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Browse");

        jLabel17.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 36, 115));
        jLabel17.setText("Cost per Month");

        jLabel18.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 36, 115));
        jLabel18.setText("License Plate");

        jLabel19.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 36, 115));
        jLabel19.setText("Year");

        jComboBox5.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox6.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTextField6.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jTextField6.setToolTipText("");

        jComboBox7.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton4.setBackground(new java.awt.Color(0, 106, 188));
        jButton4.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Search");

        jButton5.setBackground(new java.awt.Color(0, 106, 188));
        jButton5.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Update");

        javax.swing.GroupLayout tabSearchVehicleLayout = new javax.swing.GroupLayout(tabSearchVehicle);
        tabSearchVehicle.setLayout(tabSearchVehicleLayout);
        tabSearchVehicleLayout.setHorizontalGroup(
            tabSearchVehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabSearchVehicleLayout.createSequentialGroup()
                .addGroup(tabSearchVehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabSearchVehicleLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(tabSearchVehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tabSearchVehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel18)
                                .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)))
                    .addGroup(tabSearchVehicleLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jButton4)))
                .addGap(53, 53, 53)
                .addGroup(tabSearchVehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabSearchVehicleLayout.createSequentialGroup()
                        .addGroup(tabSearchVehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField4)
                            .addComponent(jComboBox6, 0, 158, Short.MAX_VALUE)
                            .addComponent(jComboBox5, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField6)
                            .addComponent(jComboBox4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox7, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(73, 73, 73)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabSearchVehicleLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(202, 202, 202))
        );
        tabSearchVehicleLayout.setVerticalGroup(
            tabSearchVehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabSearchVehicleLayout.createSequentialGroup()
                .addGroup(tabSearchVehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabSearchVehicleLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(tabSearchVehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(tabSearchVehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(tabSearchVehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(tabSearchVehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(tabSearchVehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(tabSearchVehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabSearchVehicleLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(43, 43, 43)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addGroup(tabSearchVehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addContainerGap(385, Short.MAX_VALUE))
        );

        dashTabPanel.addTab("SEARCH", tabSearchVehicle);

        tabBookVehicle.setBackground(new java.awt.Color(255, 255, 255));

        jLabel20.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabel20.setText("License Plate");

        jLabel21.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabel21.setText("Year");

        jLabel22.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabel22.setText("Make");

        jLabel23.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabel23.setText("Model");

        jLabel24.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabel24.setText("Customer Name");

        jLabel25.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabel25.setText("Address");

        jLabel26.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabel26.setText("Contact");

        jLabel27.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabel27.setText("Booking Date");

        jLabel28.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabel28.setText("No of Months");

        jButton8.setBackground(new java.awt.Color(0, 106, 188));
        jButton8.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("Get Bill");

        jButton9.setBackground(new java.awt.Color(0, 106, 188));
        jButton9.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("Book");

        jComboBox8.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTextField5.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N

        jTextField7.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N

        jTextField8.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N

        jTextField9.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jTextField9.setToolTipText("");

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jTextField10.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jTextField10.setToolTipText("");

        jTextField11.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N

        jTextField12.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N

        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setToolTipText("");
        jLabel29.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton10.setBackground(new java.awt.Color(0, 106, 188));
        jButton10.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setText("Browse");

        jLabel10.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabel10.setText("Customer Photo");
        jLabel10.setToolTipText("");

        javax.swing.GroupLayout tabBookVehicleLayout = new javax.swing.GroupLayout(tabBookVehicle);
        tabBookVehicle.setLayout(tabBookVehicleLayout);
        tabBookVehicleLayout.setHorizontalGroup(
            tabBookVehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabBookVehicleLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel20)
                .addGap(41, 41, 41)
                .addComponent(jComboBox8, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jLabel21)
                .addGap(16, 16, 16)
                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(jLabel22)
                .addGap(18, 18, 18)
                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(jLabel23)
                .addGap(18, 18, 18)
                .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(tabBookVehicleLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(tabBookVehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(tabBookVehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(104, 104, 104)
                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(tabBookVehicleLayout.createSequentialGroup()
                .addGap(690, 690, 690)
                .addComponent(jButton10))
            .addGroup(tabBookVehicleLayout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(jButton9)
                .addGap(27, 27, 27)
                .addComponent(jButton8))
            .addGroup(tabBookVehicleLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(tabBookVehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addGap(22, 22, 22)
                .addGroup(tabBookVehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabBookVehicleLayout.createSequentialGroup()
                        .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(330, 330, 330)
                        .addComponent(jLabel10))
                    .addGroup(tabBookVehicleLayout.createSequentialGroup()
                        .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel28)
                        .addGap(15, 15, 15)
                        .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        tabBookVehicleLayout.setVerticalGroup(
            tabBookVehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabBookVehicleLayout.createSequentialGroup()
                .addGroup(tabBookVehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabBookVehicleLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tabBookVehicleLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jComboBox8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tabBookVehicleLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tabBookVehicleLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tabBookVehicleLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(tabBookVehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField7)
                            .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(tabBookVehicleLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(tabBookVehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField8))))
                .addGap(30, 30, 30)
                .addGroup(tabBookVehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(tabBookVehicleLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextField12)
                    .addComponent(jTextField11))
                .addGap(48, 48, 48)
                .addGroup(tabBookVehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabBookVehicleLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tabBookVehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(tabBookVehicleLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(tabBookVehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                        .addGap(50, 50, 50)
                        .addGroup(tabBookVehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField10)
                            .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(16, 16, 16)
                .addComponent(jButton10)
                .addGap(59, 59, 59)
                .addGroup(tabBookVehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton9)
                    .addComponent(jButton8)))
        );

        dashTabPanel.addTab("BOOK", null, tabBookVehicle, "");

        dash.add(dashTabPanel, java.awt.BorderLayout.PAGE_START);
        dashTabPanel.getAccessibleContext().setAccessibleName("HOME");

        getContentPane().add(dash, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseClicked
        dashTabPanel.setSelectedIndex(0);
    }//GEN-LAST:event_btnHomeMouseClicked

    private void btnAddVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddVMouseClicked
        dashTabPanel.setSelectedIndex(1);
    }//GEN-LAST:event_btnAddVMouseClicked

    private void btnViewVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewVMouseClicked
        dashTabPanel.setSelectedIndex(2);
    }//GEN-LAST:event_btnViewVMouseClicked

    private void btnSearchVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchVMouseClicked
        dashTabPanel.setSelectedIndex(3);
    }//GEN-LAST:event_btnSearchVMouseClicked

    private void btnBookVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBookVMouseClicked
        dashTabPanel.setSelectedIndex(4);
    }//GEN-LAST:event_btnBookVMouseClicked

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed

       /* Vehicle vehicle = new Vehicle(txtLplate.getText(),(cmbYear.getSelectedItem().toString()),cmbMake.getSelectedItem(),txtModel.getText(),cmbCategory.getSelectedItem(),Integer.parseInt(txtCostpm.getText()), imgVehicle.getText());
        SaveVehicle saveVehicle = new SaveVehicle(vehicle);
        saveVehicle.saveVehicleToDatabase();*/
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseActionPerformed
        JFileChooser file = new JFileChooser();
    }//GEN-LAST:event_btnBrowseActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        txtLplate.setText("");
        cmbYear.setSelectedIndex(0);
        cmbMake.setSelectedIndex(0);
        txtModel.setText("");
        cmbCategory.setSelectedIndex(0);
        txtCostpm.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnAddV;
    private javax.swing.JLabel btnBookV;
    private javax.swing.JButton btnBrowse;
    private javax.swing.JButton btnClear;
    private javax.swing.JLabel btnClose;
    private javax.swing.JLabel btnHome;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel btnSearchV;
    private javax.swing.JLabel btnViewV;
    private javax.swing.JPanel buttonClose;
    private javax.swing.JComboBox<String> cmbCategory;
    private javax.swing.JComboBox<String> cmbMake;
    private javax.swing.JComboBox<String> cmbYear;
    private javax.swing.JPanel dash;
    private javax.swing.JTabbedPane dashTabPanel;
    private javax.swing.JPanel header;
    private javax.swing.JLabel imgVehicle;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JComboBox<String> jComboBox8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JPanel menu;
    private javax.swing.JPanel menuSlide;
    private javax.swing.JPanel meunIcons;
    private javax.swing.JPanel optionIcons;
    private javax.swing.JPanel tabAddVehicle;
    private javax.swing.JPanel tabBookVehicle;
    private javax.swing.JPanel tabHome;
    private javax.swing.JPanel tabSearchVehicle;
    private javax.swing.JPanel tabViewVehicle;
    private javax.swing.JTextField txtCostpm;
    private javax.swing.JTextField txtLplate;
    private javax.swing.JTextField txtModel;
    // End of variables declaration//GEN-END:variables

}
