/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.SaveBill;
import Controller.SaveBooking;
import Controller.SaveVehicle;
import Controller.UpdateVehicle;
import Model.Bill;
import Model.Book;
import Model.DB;
import Model.Vehicle;
import java.awt.Image;
import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import static javax.swing.UIManager.getInt;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Bawantha
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
        FillCombo();
        loadDashboard();
        btnBill.setVisible(false);
    }
    
    private String filePath;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JPanel();
        optionIcons = new javax.swing.JPanel();
        buttonClose = new javax.swing.JPanel();
        btnClose = new javax.swing.JLabel();
        menu = new javax.swing.JPanel();
        meunIcons = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        menuSlide = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnViewV = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnHome = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnAddV = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnSearchV = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btnBookV = new javax.swing.JLabel();
        dash = new javax.swing.JPanel();
        dashTabPanel = new javax.swing.JTabbedPane();
        tabHome = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        txtNOV = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        txtNOB = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        tabViewVehicle = new javax.swing.JPanel();
        btnView = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableVehicle = new javax.swing.JTable();
        jPanel15 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        tabAddVehicle = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtLplate = new javax.swing.JTextField();
        cmbMake = new javax.swing.JComboBox<>();
        cmbYear = new javax.swing.JComboBox<>();
        txtModel = new javax.swing.JTextField();
        cmbCategory = new javax.swing.JComboBox<>();
        txtCostpm = new javax.swing.JTextField();
        imgVehicle = new javax.swing.JLabel();
        btnBrowse = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        txtAddError = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        tabSearchVehicle = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        txtSCostPerMonth = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        imgSVehicle = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        btnBrowseSearch = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtSModel = new javax.swing.JTextField();
        cmbSPlateNo = new javax.swing.JComboBox<>();
        btnSearch = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        txtSYear = new javax.swing.JTextField();
        txtSCategory = new javax.swing.JTextField();
        txtSMake = new javax.swing.JTextField();
        txtSearchError = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        tabBookVehicle = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        btnBill = new javax.swing.JButton();
        btnBSearch = new javax.swing.JButton();
        cmbBLplate = new javax.swing.JComboBox<>();
        txtBYear = new javax.swing.JTextField();
        txtBMake = new javax.swing.JTextField();
        txtBCostpMonth = new javax.swing.JTextField();
        txtCName = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtCAddress = new javax.swing.JTextArea();
        txtFinalBill = new javax.swing.JTextField();
        txtBNo = new javax.swing.JTextField();
        txtBnom = new javax.swing.JTextField();
        imgCustomer = new javax.swing.JLabel();
        btnBBrowse = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        btnCalculate = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        txtBookError = new javax.swing.JLabel();
        txtCContact = new javax.swing.JTextField();
        txtBillAmt = new javax.swing.JTextField();
        txtAdvPay = new javax.swing.JTextField();
        btnBook = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        txtBModel = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        txtBDate = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1350, 1000));

        header.setBackground(new java.awt.Color(23, 35, 76));
        header.setPreferredSize(new java.awt.Dimension(900, 64));
        header.setRequestFocusEnabled(false);
        header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        optionIcons.setPreferredSize(new java.awt.Dimension(150, 50));

        buttonClose.setBackground(new java.awt.Color(23, 35, 76));
        buttonClose.setToolTipText("");
        buttonClose.setLayout(new java.awt.BorderLayout());

        btnClose.setBackground(new java.awt.Color(0, 106, 188));
        btnClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnClose.setIcon(new javax.swing.ImageIcon("E:\\Downloads\\icons8-cancel-64.png")); // NOI18N
        btnClose.setToolTipText("");
        buttonClose.add(btnClose, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout optionIconsLayout = new javax.swing.GroupLayout(optionIcons);
        optionIcons.setLayout(optionIconsLayout);
        optionIconsLayout.setHorizontalGroup(
            optionIconsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 64, Short.MAX_VALUE)
            .addGroup(optionIconsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(optionIconsLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(buttonClose, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        optionIconsLayout.setVerticalGroup(
            optionIconsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 64, Short.MAX_VALUE)
            .addGroup(optionIconsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(optionIconsLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(buttonClose, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        header.add(optionIcons, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 0, 64, 64));

        getContentPane().add(header, java.awt.BorderLayout.PAGE_START);

        menu.setBackground(new java.awt.Color(65, 76, 80));
        menu.setPreferredSize(new java.awt.Dimension(270, 505));
        menu.setLayout(new java.awt.BorderLayout());

        meunIcons.setBackground(new java.awt.Color(23, 35, 76));
        meunIcons.setPreferredSize(new java.awt.Dimension(64, 625));
        meunIcons.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(23, 35, 76));
        jPanel6.setLayout(new java.awt.BorderLayout());

        jLabel30.setIcon(new javax.swing.ImageIcon("E:\\Downloads\\icons8-transaction-list-64.png")); // NOI18N
        jPanel6.add(jLabel30, java.awt.BorderLayout.CENTER);

        meunIcons.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 256, 64, 64));

        jPanel7.setBackground(new java.awt.Color(23, 35, 76));
        jPanel7.setForeground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new java.awt.BorderLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon("E:\\Downloads\\icons8-home-64.png")); // NOI18N
        jLabel6.setToolTipText("");
        jPanel7.add(jLabel6, java.awt.BorderLayout.CENTER);

        meunIcons.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 64, 64));

        jPanel8.setBackground(new java.awt.Color(23, 35, 76));
        jPanel8.setLayout(new java.awt.BorderLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon("E:\\Downloads\\icons8-car-rental-64.png")); // NOI18N
        jPanel8.add(jLabel7, java.awt.BorderLayout.CENTER);

        meunIcons.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 64, 64, 64));

        jPanel9.setBackground(new java.awt.Color(23, 35, 76));
        jPanel9.setLayout(new java.awt.BorderLayout());

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon("E:\\Downloads\\icons8-add-40.png")); // NOI18N
        jLabel8.setToolTipText("");
        jPanel9.add(jLabel8, java.awt.BorderLayout.CENTER);

        meunIcons.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 128, 64, 64));

        jPanel10.setBackground(new java.awt.Color(23, 35, 76));
        jPanel10.setLayout(new java.awt.BorderLayout());

        jLabel9.setIcon(new javax.swing.ImageIcon("E:\\Downloads\\icons8-search-64.png")); // NOI18N
        jLabel9.setToolTipText("");
        jPanel10.add(jLabel9, java.awt.BorderLayout.CENTER);

        meunIcons.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 192, 64, 64));

        menu.add(meunIcons, java.awt.BorderLayout.LINE_START);

        menuSlide.setBackground(new java.awt.Color(0, 48, 131));
        menuSlide.setForeground(new java.awt.Color(2, 127, 255));
        menuSlide.setToolTipText("");
        menuSlide.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 48, 131));
        jPanel1.setLayout(new java.awt.BorderLayout());

        btnViewV.setBackground(new java.awt.Color(2, 127, 255));
        btnViewV.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        btnViewV.setForeground(new java.awt.Color(255, 255, 255));
        btnViewV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnViewV.setText("VIEW VEHICLE");
        btnViewV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnViewVMouseClicked(evt);
            }
        });
        jPanel1.add(btnViewV, java.awt.BorderLayout.CENTER);

        menuSlide.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 64, 205, 64));

        jPanel2.setBackground(new java.awt.Color(0, 48, 131));
        jPanel2.setLayout(new java.awt.BorderLayout());

        btnHome.setBackground(new java.awt.Color(2, 127, 255));
        btnHome.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        btnHome.setForeground(new java.awt.Color(255, 255, 255));
        btnHome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnHome.setText("HOME");
        btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHomeMouseClicked(evt);
            }
        });
        jPanel2.add(btnHome, java.awt.BorderLayout.CENTER);

        menuSlide.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 205, 64));

        jPanel3.setBackground(new java.awt.Color(0, 48, 131));
        jPanel3.setLayout(new java.awt.BorderLayout());

        btnAddV.setBackground(new java.awt.Color(2, 127, 255));
        btnAddV.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        btnAddV.setForeground(new java.awt.Color(255, 255, 255));
        btnAddV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAddV.setText("ADD VEHICLE");
        btnAddV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddVMouseClicked(evt);
            }
        });
        jPanel3.add(btnAddV, java.awt.BorderLayout.CENTER);

        menuSlide.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 128, 220, 64));

        jPanel4.setBackground(new java.awt.Color(0, 48, 131));
        jPanel4.setLayout(new java.awt.BorderLayout());

        btnSearchV.setBackground(new java.awt.Color(2, 127, 255));
        btnSearchV.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        btnSearchV.setForeground(new java.awt.Color(255, 255, 255));
        btnSearchV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSearchV.setText("SEARCH VEHICLE");
        btnSearchV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSearchVMouseClicked(evt);
            }
        });
        jPanel4.add(btnSearchV, java.awt.BorderLayout.CENTER);

        menuSlide.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 192, 205, 64));

        jPanel5.setBackground(new java.awt.Color(0, 48, 131));
        jPanel5.setLayout(new java.awt.BorderLayout());

        btnBookV.setBackground(new java.awt.Color(0, 48, 131));
        btnBookV.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        btnBookV.setForeground(new java.awt.Color(255, 255, 255));
        btnBookV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnBookV.setText("BOOK VEHICLE");
        btnBookV.setToolTipText("");
        btnBookV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBookVMouseClicked(evt);
            }
        });
        jPanel5.add(btnBookV, java.awt.BorderLayout.CENTER);

        menuSlide.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 256, 205, 64));

        menu.add(menuSlide, java.awt.BorderLayout.CENTER);

        getContentPane().add(menu, java.awt.BorderLayout.LINE_START);

        dash.setBackground(new java.awt.Color(255, 255, 255));
        dash.setLayout(new java.awt.BorderLayout());

        dashTabPanel.setBackground(new java.awt.Color(153, 204, 255));
        dashTabPanel.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N

        tabHome.setBackground(new java.awt.Color(153, 204, 255));
        tabHome.setToolTipText("");
        tabHome.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        tabHome.setInheritsPopupMenu(true);
        tabHome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel11.setBackground(new java.awt.Color(71, 87, 112));
        jPanel11.setToolTipText("");
        jPanel11.setPreferredSize(new java.awt.Dimension(400, 0));

        jLabel12.setBackground(new java.awt.Color(0, 48, 131));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("NO OF VEHICLES");

        txtNOV.setBackground(new java.awt.Color(0, 48, 131));
        txtNOV.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        txtNOV.setForeground(new java.awt.Color(255, 255, 255));
        txtNOV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtNOV.setText("0");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
            .addComponent(txtNOV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNOV, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE))
        );

        tabHome.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 60, 410, 230));

        jPanel12.setBackground(new java.awt.Color(71, 87, 112));
        jPanel12.setToolTipText("");

        jLabel32.setBackground(new java.awt.Color(0, 48, 131));
        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setText("NO OF BOOKINGS");

        txtNOB.setBackground(new java.awt.Color(0, 48, 131));
        txtNOB.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        txtNOB.setForeground(new java.awt.Color(255, 255, 255));
        txtNOB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtNOB.setText("0");
        txtNOB.setToolTipText("");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addComponent(txtNOB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNOB, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE))
        );

        tabHome.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(579, 60, -1, 230));

        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon("E:\\Downloads\\1600x900_Fleet_Web_Header_14_tcm-11-895140.jpg")); // NOI18N
        jPanel13.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1210, 890));

        tabHome.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1210, 890));

        dashTabPanel.addTab("HOME", tabHome);

        tabViewVehicle.setBackground(new java.awt.Color(153, 204, 255));
        tabViewVehicle.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnView.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        btnView.setText("VIEW ALL");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });
        tabViewVehicle.add(btnView, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 36, -1, -1));

        tableVehicle.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tableVehicle.setForeground(new java.awt.Color(0, 48, 131));
        tableVehicle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "License Plate", "Year", "Make", "Model", "Category", "Cost Per Month"
            }
        ));
        tableVehicle.setGridColor(new java.awt.Color(255, 255, 255));
        tableVehicle.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tableVehicle.setShowHorizontalLines(false);
        tableVehicle.setShowVerticalLines(false);
        jScrollPane1.setViewportView(tableVehicle);

        tabViewVehicle.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 85, 1055, 591));

        jPanel15.setLayout(new java.awt.BorderLayout());

        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel37.setIcon(new javax.swing.ImageIcon("E:\\Downloads\\blue-background-pinterest-plain-aesthetic-with-stars-scaled.jpg")); // NOI18N
        jPanel15.add(jLabel37, java.awt.BorderLayout.CENTER);

        tabViewVehicle.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1220, 890));

        dashTabPanel.addTab("VIEW", tabViewVehicle);

        tabAddVehicle.setBackground(new java.awt.Color(153, 204, 255));
        tabAddVehicle.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 36, 115));
        jLabel1.setText("License Plate");
        tabAddVehicle.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 56, -1, -1));

        jLabel2.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 36, 115));
        jLabel2.setText("Year");
        tabAddVehicle.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 118, -1, -1));

        jLabel3.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 36, 115));
        jLabel3.setText("Make");
        tabAddVehicle.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 175, -1, -1));

        jLabel4.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 36, 115));
        jLabel4.setText("Model");
        tabAddVehicle.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 241, -1, -1));

        jLabel5.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 36, 115));
        jLabel5.setText("Category");
        tabAddVehicle.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 307, -1, -1));

        jLabel11.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 36, 115));
        jLabel11.setText("Cost per Month");
        tabAddVehicle.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 368, -1, 28));

        txtLplate.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        tabAddVehicle.add(txtLplate, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 53, 158, -1));

        cmbMake.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        cmbMake.setForeground(new java.awt.Color(0, 36, 115));
        cmbMake.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Make--", "ACURA", "ASTON-MARTIN", "AUDI", "BENTLY", "BMW", "CADILLAC", "CHERVOLET", "FIAT", "FORD", "HONDA", "HYUNDAI", "JAGUAR", "JEEP", "KIA", "LAND ROVER", "LEXUS", "MAZDA", "MERCEDES", "MINI", "MITSUBISHI", "NISSAN", "PEUGOT", "RENAULT", "SUBARU", "SUZUKI", "TESLA", "TOYOTA", "VOLKSWAGEN" }));
        tabAddVehicle.add(cmbMake, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 172, 158, -1));

        cmbYear.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        cmbYear.setForeground(new java.awt.Color(0, 36, 115));
        cmbYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Year--", "2024", "2023", "2022", "2021", "2020", "2019", "2018", "2017", "2016", "2015", "2014", "2013", "2012", "2011", "2010", "2009", "2008", "2007", "2006", "2005", "2004", "2003", "2002", "2001", "2000", "1999", "1998", "1997", "1996", "1995", "1994", "1993", "1992", "1991", "1990" }));
        cmbYear.setToolTipText("");
        tabAddVehicle.add(cmbYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 115, 158, -1));

        txtModel.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        txtModel.setToolTipText("");
        tabAddVehicle.add(txtModel, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 238, 158, -1));

        cmbCategory.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        cmbCategory.setForeground(new java.awt.Color(0, 36, 115));
        cmbCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Category--", "GENERAL", "LUXUARY", "PREMIUM", "SUV", "VAN" }));
        tabAddVehicle.add(cmbCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 304, 158, -1));

        txtCostpm.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        txtCostpm.setToolTipText("");
        tabAddVehicle.add(txtCostpm, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 368, 158, -1));

        imgVehicle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgVehicle.setText("Photo");
        imgVehicle.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tabAddVehicle.add(imgVehicle, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 50, 407, 343));

        btnBrowse.setBackground(new java.awt.Color(0, 106, 188));
        btnBrowse.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        btnBrowse.setForeground(new java.awt.Color(255, 255, 255));
        btnBrowse.setText("Browse");
        btnBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseActionPerformed(evt);
            }
        });
        tabAddVehicle.add(btnBrowse, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 430, -1, -1));

        btnSave.setBackground(new java.awt.Color(0, 106, 188));
        btnSave.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        tabAddVehicle.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 464, -1, -1));

        btnClear.setBackground(new java.awt.Color(0, 106, 188));
        btnClear.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        btnClear.setForeground(new java.awt.Color(255, 255, 255));
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        tabAddVehicle.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 464, -1, -1));

        txtAddError.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        txtAddError.setForeground(new java.awt.Color(255, 0, 0));
        txtAddError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtAddError.setText(".");
        tabAddVehicle.add(txtAddError, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 560, 434, 53));

        jPanel14.setLayout(new java.awt.BorderLayout());

        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel36.setIcon(new javax.swing.ImageIcon("E:\\Downloads\\blue-background-pinterest-plain-aesthetic-with-stars-scaled.jpg")); // NOI18N
        jPanel14.add(jLabel36, java.awt.BorderLayout.CENTER);

        tabAddVehicle.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 890));

        dashTabPanel.addTab("ADD", tabAddVehicle);

        tabSearchVehicle.setBackground(new java.awt.Color(153, 204, 255));
        tabSearchVehicle.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 36, 115));
        jLabel13.setText("Make");
        tabSearchVehicle.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 218, -1, -1));

        txtSCostPerMonth.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        txtSCostPerMonth.setToolTipText("");
        tabSearchVehicle.add(txtSCostPerMonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 411, 158, -1));

        jLabel14.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 36, 115));
        jLabel14.setText("Model");
        tabSearchVehicle.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 284, -1, -1));

        imgSVehicle.setBackground(java.awt.Color.white);
        imgSVehicle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgSVehicle.setToolTipText("");
        imgSVehicle.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tabSearchVehicle.add(imgSVehicle, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 50, 433, 359));

        jLabel16.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 36, 115));
        jLabel16.setText("Category");
        tabSearchVehicle.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 350, -1, -1));

        btnBrowseSearch.setBackground(new java.awt.Color(0, 106, 188));
        btnBrowseSearch.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        btnBrowseSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnBrowseSearch.setText("Browse");
        btnBrowseSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseSearchActionPerformed(evt);
            }
        });
        tabSearchVehicle.add(btnBrowseSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 440, -1, -1));

        jLabel17.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 36, 115));
        jLabel17.setText("Cost per Month");
        tabSearchVehicle.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 417, -1, -1));

        jLabel18.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 36, 115));
        jLabel18.setText("License Plate");
        tabSearchVehicle.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 56, -1, -1));

        jLabel19.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 36, 115));
        jLabel19.setText("Year");
        tabSearchVehicle.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 161, -1, -1));

        txtSModel.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        txtSModel.setToolTipText("");
        tabSearchVehicle.add(txtSModel, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 281, 158, -1));

        cmbSPlateNo.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        cmbSPlateNo.setToolTipText("");
        tabSearchVehicle.add(cmbSPlateNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 53, 158, -1));

        btnSearch.setBackground(new java.awt.Color(0, 106, 188));
        btnSearch.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        tabSearchVehicle.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 99, -1, -1));

        btnUpdate.setBackground(new java.awt.Color(0, 106, 188));
        btnUpdate.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        tabSearchVehicle.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 488, -1, -1));

        btnDelete.setBackground(new java.awt.Color(0, 106, 188));
        btnDelete.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("Delete");
        btnDelete.setToolTipText("");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        tabSearchVehicle.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 488, -1, -1));

        txtSYear.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        txtSYear.setToolTipText("");
        tabSearchVehicle.add(txtSYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 158, 158, -1));

        txtSCategory.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        txtSCategory.setToolTipText("");
        tabSearchVehicle.add(txtSCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 344, 158, -1));

        txtSMake.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        txtSMake.setToolTipText("");
        tabSearchVehicle.add(txtSMake, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 215, 158, -1));

        txtSearchError.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        txtSearchError.setForeground(new java.awt.Color(255, 0, 0));
        txtSearchError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtSearchError.setText(".");
        tabSearchVehicle.add(txtSearchError, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 560, 434, 53));

        jPanel16.setLayout(new java.awt.BorderLayout());

        jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel38.setIcon(new javax.swing.ImageIcon("E:\\Downloads\\blue-background-pinterest-plain-aesthetic-with-stars-scaled.jpg")); // NOI18N
        jPanel16.add(jLabel38, java.awt.BorderLayout.CENTER);

        tabSearchVehicle.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1180, 890));

        dashTabPanel.addTab("SEARCH", tabSearchVehicle);

        tabBookVehicle.setBackground(new java.awt.Color(153, 204, 255));
        tabBookVehicle.setForeground(new java.awt.Color(0, 36, 115));
        tabBookVehicle.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 36, 115));
        jLabel20.setText("License Plate");
        tabBookVehicle.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, 30));

        jLabel21.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 36, 115));
        jLabel21.setText("Year");
        tabBookVehicle.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, -1, 30));

        jLabel22.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 36, 115));
        jLabel22.setText("Make");
        tabBookVehicle.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 50, -1, 28));

        jLabel23.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 36, 115));
        jLabel23.setText("Model");
        tabBookVehicle.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(761, 48, -1, 28));

        jLabel24.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 36, 115));
        jLabel24.setText("Customer Name");
        tabBookVehicle.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, 30));

        jLabel25.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 36, 115));
        jLabel25.setText("Address");
        tabBookVehicle.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 93, 140));

        jLabel26.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 36, 115));
        jLabel26.setText("Final Bill Amount (Rs.)");
        tabBookVehicle.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 640, 180, 28));

        jLabel27.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 36, 115));
        jLabel27.setText("Booking No");
        tabBookVehicle.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 123, 30));

        jLabel28.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 36, 115));
        jLabel28.setText("Cost Per Month");
        tabBookVehicle.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, 30));

        btnBill.setBackground(new java.awt.Color(0, 106, 188));
        btnBill.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        btnBill.setForeground(new java.awt.Color(255, 255, 255));
        btnBill.setText("Get Bill");
        btnBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBillActionPerformed(evt);
            }
        });
        tabBookVehicle.add(btnBill, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 690, -1, -1));

        btnBSearch.setBackground(new java.awt.Color(0, 106, 188));
        btnBSearch.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        btnBSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnBSearch.setText("SEARCH");
        btnBSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBSearchActionPerformed(evt);
            }
        });
        tabBookVehicle.add(btnBSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 100, -1, -1));

        cmbBLplate.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        tabBookVehicle.add(cmbBLplate, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 146, -1));

        txtBYear.setEditable(false);
        txtBYear.setBackground(java.awt.Color.white);
        txtBYear.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        tabBookVehicle.add(txtBYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, 86, -1));

        txtBMake.setEditable(false);
        txtBMake.setBackground(java.awt.Color.white);
        txtBMake.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        tabBookVehicle.add(txtBMake, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 50, 99, -1));

        txtBCostpMonth.setEditable(false);
        txtBCostpMonth.setBackground(java.awt.Color.white);
        txtBCostpMonth.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        tabBookVehicle.add(txtBCostpMonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 150, 30));

        txtCName.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        txtCName.setToolTipText("");
        tabBookVehicle.add(txtCName, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 150, -1));

        txtCAddress.setColumns(20);
        txtCAddress.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        txtCAddress.setRows(5);
        jScrollPane2.setViewportView(txtCAddress);

        tabBookVehicle.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, -1, 140));

        txtFinalBill.setEditable(false);
        txtFinalBill.setBackground(new java.awt.Color(255, 255, 255));
        txtFinalBill.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        txtFinalBill.setToolTipText("");
        tabBookVehicle.add(txtFinalBill, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 640, 150, -1));

        txtBNo.setEditable(false);
        txtBNo.setBackground(java.awt.Color.white);
        txtBNo.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        tabBookVehicle.add(txtBNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 150, 32));

        txtBnom.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        tabBookVehicle.add(txtBnom, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 170, 86, 32));

        imgCustomer.setBackground(new java.awt.Color(255, 255, 255));
        imgCustomer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgCustomer.setToolTipText("");
        imgCustomer.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tabBookVehicle.add(imgCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(601, 280, 350, 300));

        btnBBrowse.setBackground(new java.awt.Color(0, 106, 188));
        btnBBrowse.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        btnBBrowse.setForeground(new java.awt.Color(255, 255, 255));
        btnBBrowse.setText("Browse");
        btnBBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBBrowseActionPerformed(evt);
            }
        });
        tabBookVehicle.add(btnBBrowse, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 590, -1, -1));

        jLabel10.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 36, 115));
        jLabel10.setText("Customer Photo");
        jLabel10.setToolTipText("");
        tabBookVehicle.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 250, -1, 32));

        btnCalculate.setBackground(new java.awt.Color(0, 106, 188));
        btnCalculate.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        btnCalculate.setForeground(new java.awt.Color(255, 255, 255));
        btnCalculate.setText("Calculate");
        btnCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateActionPerformed(evt);
            }
        });
        tabBookVehicle.add(btnCalculate, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 700, -1, -1));

        jLabel29.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 36, 115));
        jLabel29.setText("Contact");
        tabBookVehicle.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 490, 80, 28));

        jLabel31.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(0, 36, 115));
        jLabel31.setText("Bill Amount (Rs.)");
        tabBookVehicle.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 560, 180, 28));

        txtBookError.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtBookError.setForeground(new java.awt.Color(255, 0, 0));
        txtBookError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtBookError.setText(".");
        txtBookError.setToolTipText("");
        tabBookVehicle.add(txtBookError, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 730, 810, 60));

        txtCContact.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        txtCContact.setToolTipText("");
        tabBookVehicle.add(txtCContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 490, 150, -1));

        txtBillAmt.setEditable(false);
        txtBillAmt.setBackground(new java.awt.Color(255, 255, 255));
        txtBillAmt.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        txtBillAmt.setToolTipText("");
        tabBookVehicle.add(txtBillAmt, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 560, 150, -1));

        txtAdvPay.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        txtAdvPay.setToolTipText("");
        tabBookVehicle.add(txtAdvPay, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 600, 150, -1));

        btnBook.setBackground(new java.awt.Color(0, 106, 188));
        btnBook.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        btnBook.setForeground(new java.awt.Color(255, 255, 255));
        btnBook.setText("Book");
        btnBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookActionPerformed(evt);
            }
        });
        tabBookVehicle.add(btnBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 690, -1, -1));

        jLabel33.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(0, 36, 115));
        jLabel33.setText("No of Months");
        tabBookVehicle.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 170, -1, 30));

        txtBModel.setEditable(false);
        txtBModel.setBackground(java.awt.Color.white);
        txtBModel.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        tabBookVehicle.add(txtBModel, new org.netbeans.lib.awtextra.AbsoluteConstraints(827, 48, 94, -1));

        jLabel34.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(0, 36, 115));
        jLabel34.setText("Booking Date");
        tabBookVehicle.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, 123, 30));

        txtBDate.setEditable(false);
        txtBDate.setBackground(java.awt.Color.white);
        txtBDate.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        tabBookVehicle.add(txtBDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 170, 150, 32));

        jLabel35.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(0, 36, 115));
        jLabel35.setText("Advance Payment (Rs.)");
        tabBookVehicle.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 600, 180, 28));

        jPanel17.setLayout(new java.awt.BorderLayout());

        jLabel39.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel39.setIcon(new javax.swing.ImageIcon("E:\\Downloads\\blue-background-pinterest-plain-aesthetic-with-stars-scaled.jpg")); // NOI18N
        jLabel39.setToolTipText("");
        jPanel17.add(jLabel39, java.awt.BorderLayout.CENTER);

        tabBookVehicle.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1230, 890));

        dashTabPanel.addTab("BOOK", null, tabBookVehicle, "");

        dash.add(dashTabPanel, java.awt.BorderLayout.PAGE_START);
        dashTabPanel.getAccessibleContext().setAccessibleName("HOME");

        getContentPane().add(dash, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseClicked
        dashTabPanel.setSelectedIndex(0);
    }//GEN-LAST:event_btnHomeMouseClicked

    private void btnAddVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddVMouseClicked
        dashTabPanel.setSelectedIndex(2);
    }//GEN-LAST:event_btnAddVMouseClicked

    private void btnViewVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewVMouseClicked
        dashTabPanel.setSelectedIndex(1);
    }//GEN-LAST:event_btnViewVMouseClicked

    private void btnSearchVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchVMouseClicked
        dashTabPanel.setSelectedIndex(3);
    }//GEN-LAST:event_btnSearchVMouseClicked

    private void btnBookVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBookVMouseClicked
        dashTabPanel.setSelectedIndex(4);
    }//GEN-LAST:event_btnBookVMouseClicked

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        validateAdd();
        if(txtAddError.getText().equals("")){
        Vehicle vehicle = new Vehicle(txtLplate.getText(),Integer.parseInt(cmbYear.getSelectedItem().toString()),cmbMake.getSelectedItem().toString(),txtModel.getText(),cmbCategory.getSelectedItem().toString(),Integer.parseInt(txtCostpm.getText()), filePath);
        SaveVehicle saveVehicle = new SaveVehicle(vehicle);
        saveVehicle.saveVehicleToDatabase();
        RefreshAddTab();
        }
        else
            JOptionPane.showMessageDialog(this,"Please fill the form Properly","Error",JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseActionPerformed
        JFileChooser file = new JFileChooser();
        file.setCurrentDirectory(new File(System.getProperty("user.home")));
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Image Files", "jpg", "png", "gif", "jpeg");
        file.setFileFilter(filter);
        int result = file.showSaveDialog(null);
        if(result == JFileChooser.APPROVE_OPTION){
            File selectedFile = file.getSelectedFile();
            filePath = selectedFile.getAbsolutePath();
            imgVehicle.setIcon(ResizeImage(filePath));
        }
        else if(result == JFileChooser.CANCEL_OPTION){
            System.out.println("No File Selected");
        }
    }//GEN-LAST:event_btnBrowseActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        txtLplate.setText("");
        cmbYear.setSelectedIndex(0);
        cmbMake.setSelectedIndex(0);
        txtModel.setText("");
        cmbCategory.setSelectedIndex(0);
        txtCostpm.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed

        try {
            Connection con = DB.createConnection();
            String sql = ("select LPlate,Year,Make,Model,Category,Cost_per_month from vehicles");
            PreparedStatement statement = con.prepareStatement(sql);
            ResultSet rs = statement.executeQuery();
            DefaultTableModel tm = (DefaultTableModel)tableVehicle.getModel();
            tm.setRowCount(0);
            tm.getRowCount();
            while (rs.next()){
                Object obj[] = {rs.getString(1),rs.getInt(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getInt(6)};
                tm.addRow(obj);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex);
        }
        
        
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        try{
            Connection con = DB.createConnection();
            String sql = ("select * from vehicles where LPlate ='"+cmbSPlateNo.getSelectedItem().toString()+"' ");
            PreparedStatement statement = con.prepareStatement(sql);
            ResultSet rs = statement.executeQuery();
            while (rs.next()){
                txtSYear.setText(rs.getString(2));
                txtSMake.setText(rs.getString(3));
                txtSModel.setText(rs.getString(4));
                txtSCategory.setText(rs.getString(5));
                txtSCostPerMonth.setText(rs.getString(6));  
                filePath = rs.getString(7);
            }
            ImageIcon img = new ImageIcon(filePath);
            imgSVehicle.setIcon(ResizeUpdateImage(filePath));
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex);
        }
            
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnBSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBSearchActionPerformed
        txtBNo.setText(incrementID(getBookingId())); 
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd");  
        LocalDateTime now = LocalDateTime.now();  
        txtBDate.setText(dtf.format(now));  
        try{
            Connection con = DB.createConnection();
            String sql = ("select * from vehicles where LPlate ='"+cmbBLplate.getSelectedItem().toString()+"' ");
            PreparedStatement statement = con.prepareStatement(sql);
            ResultSet rs = statement.executeQuery();
            while (rs.next()){
                txtBYear.setText(rs.getString(2));
                txtBMake.setText(rs.getString(3));
                txtBModel.setText(rs.getString(4));
                txtBCostpMonth.setText(rs.getString(6));  
            }
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex);
        }
    }//GEN-LAST:event_btnBSearchActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        validateSearch();
        if (txtSearchError.getText().equals("")){
        Vehicle vehicle = new Vehicle(cmbSPlateNo.getSelectedItem().toString(),Integer.parseInt(txtSYear.getText()),txtSMake.getText(),txtSModel.getText(),txtSCategory.getText(),Integer.parseInt(txtSCostPerMonth.getText()), filePath);
        UpdateVehicle uv = new UpdateVehicle(vehicle);
        uv.updateVehicleDatabase();
        }
        else
            JOptionPane.showMessageDialog(this,"Please fill the form Properly","Error",JOptionPane.ERROR_MESSAGE);        
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnBBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBBrowseActionPerformed
        JFileChooser file = new JFileChooser();
        file.setCurrentDirectory(new File(System.getProperty("user.home")));
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Image Files", "jpg", "png", "gif", "jpeg");
        file.setFileFilter(filter);
        int result = file.showSaveDialog(null);
        if(result == JFileChooser.APPROVE_OPTION){
            File selectedFile = file.getSelectedFile();
            filePath = selectedFile.getAbsolutePath();
            imgCustomer.setIcon(ResizeCustomerImage(filePath));
        }
        else if(result == JFileChooser.CANCEL_OPTION){
            System.out.println("No File Selected");
        }
    }//GEN-LAST:event_btnBBrowseActionPerformed

    private void btnBrowseSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseSearchActionPerformed
        JFileChooser file = new JFileChooser("E:\\Downloads\\");
        //file.setCurrentDirectory(new File(System.getProperty("user.home")));
        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.Images","jpg","gif","png");
        file.addChoosableFileFilter(filter);
        int result = file.showSaveDialog(null);
        if(result == JFileChooser.APPROVE_OPTION){
            File selectedFile = file.getSelectedFile();
            filePath = selectedFile.getAbsolutePath();
            imgSVehicle.setIcon(ResizeUpdateImage(filePath));
        }
        else if(result == JFileChooser.CANCEL_OPTION){
            System.out.println("No File Selected");
        }
    }//GEN-LAST:event_btnBrowseSearchActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        try{
            int input = JOptionPane.showConfirmDialog(this,"Are you sure yow want to delete","Warning", JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE);
            if(input == 0)
            {
                Connection con = DB.createConnection();
                String sql = "delete from vehicles where LPlate = '"+cmbSPlateNo.getSelectedItem().toString()+"'";
                PreparedStatement statement = con.prepareStatement(sql);  
                int i = statement.executeUpdate();
                if(i>=1){
                    JOptionPane.showMessageDialog(null,"Data Deleted Successfully!","Information",JOptionPane.INFORMATION_MESSAGE);
                    RefreshSearchTab();
                }
                else{
                    JOptionPane.showMessageDialog(null,"Data couldnt delete","Error",JOptionPane.INFORMATION_MESSAGE);
                }
            } 
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(this,ex);
        }
        
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed
        validateBooking();
        if(txtBookError.getText() == "")
        {
            calculateBill();
            btnBook.setVisible(true);
        }
            
    }//GEN-LAST:event_btnCalculateActionPerformed

    private void btnBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookActionPerformed
        if(txtBookError.getText() != ""){
            JOptionPane.showMessageDialog(this,"Please Fill Out The Form Properly","Error",JOptionPane.ERROR_MESSAGE);
        }
        else{
            Book book = new Book(txtBNo.getText(),txtBDate.getText(),Integer.parseInt(txtBnom.getText()),txtCName.getText(),txtCAddress.getText(),Integer.parseInt(txtCContact.getText()),filePath);
            Bill bill = new Bill((incrementID(getBillID())),txtBDate.getText(),Double.parseDouble(txtBillAmt.getText()),Double.parseDouble(txtAdvPay.getText()),Double.parseDouble(txtFinalBill.getText()));
            Vehicle vehicle = new Vehicle();
            vehicle.setID(cmbBLplate.getSelectedItem().toString());
            SaveBooking sbook = new SaveBooking(book, vehicle);
            SaveBill sbill = new SaveBill(bill,book);
            sbook.saveToDatabase();
            sbill.saveToDatabase();
            btnBill.setVisible(true);
        }
    }//GEN-LAST:event_btnBookActionPerformed

    private void btnBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBillActionPerformed
      BillReport br = new BillReport(this, true);
      br.setVisible(true);
    }//GEN-LAST:event_btnBillActionPerformed

    public ImageIcon ResizeImage(String ImagePath){
        ImageIcon MyImage = new ImageIcon(ImagePath);
        Image img = MyImage.getImage();
        Image newImg = img.getScaledInstance(imgVehicle.getWidth(),imgVehicle.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        return image;
    }
    
    public ImageIcon ResizeUpdateImage(String ImagePath){
        ImageIcon MyImage = new ImageIcon(ImagePath);
        Image img = MyImage.getImage();
        Image newImg = img.getScaledInstance(imgSVehicle.getWidth(),imgSVehicle.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        return image;
    }
    
    public ImageIcon ResizeCustomerImage(String ImagePath){
       ImageIcon MyImage = new ImageIcon(ImagePath);
        Image img = MyImage.getImage();
        Image newImg = img.getScaledInstance(imgCustomer.getWidth(),imgCustomer.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        return image; 
    }
    
    private void FillCombo(){
        try{
            cmbSPlateNo.removeAllItems();
            cmbBLplate.removeAllItems();
            Connection con = DB.createConnection();
            String sql = "select * from vehicles";
            PreparedStatement statement = con.prepareStatement(sql);
            ResultSet rs = statement.executeQuery();
            while (rs.next()){
                String Lplate = rs.getString(1);
                cmbSPlateNo.addItem(Lplate);
                cmbBLplate.addItem(Lplate);
            }
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(this,ex);
        }
    }
    
    private void RefreshAddTab(){
        FillCombo();
        txtLplate.setText("");
        cmbYear.setSelectedIndex(0);
        cmbMake.setSelectedIndex(0);
        txtModel.setText("");
        cmbCategory.setSelectedIndex(0);
        txtCostpm.setText("");
    }
    
    private void RefreshSearchTab(){
        FillCombo();
        cmbSPlateNo.setSelectedIndex(-1);
        txtSYear.setText("");
        txtSMake.setText("");
        txtSModel.setText("");
        txtSCategory.setText("");
        txtSCostPerMonth.setText("");
    }
    
    private void calculateBill()
    {
        try{
        double billAmt = Integer.parseInt(txtBCostpMonth.getText()) * Integer.parseInt(txtBnom.getText());
        double finalBill = (billAmt) - Double.parseDouble(txtAdvPay.getText());
        txtBillAmt.setText(String.valueOf(billAmt));
        txtFinalBill.setText(String.valueOf(finalBill));
        }
        catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(this,"Please Enter valid numbers ","Error",JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private String getBookingId(){
        try{
                String bid = null;
                Connection con = DB.createConnection();
                String sql = "SELECT Bk_No FROM booking ORDER BY Bk_no DESC LIMIT 1;";
                PreparedStatement statement = con.prepareStatement(sql);  
                ResultSet rs = statement.executeQuery();
                while (rs.next()){
                    bid = rs.getString(1);
                }
                return bid;
            } 
        catch(Exception ex){
            JOptionPane.showMessageDialog(this,ex);
        }
        return null;
    }
    
    private String getBillID(){
         try{
                String billID = null;
                Connection con = DB.createConnection();
                String sql = "SELECT Bill_No FROM billing ORDER BY Bill_No DESC LIMIT 1;";
                PreparedStatement statement = con.prepareStatement(sql);  
                ResultSet rs = statement.executeQuery();
                while (rs.next()){
                    billID = rs.getString(1);
                }
                return billID;
            } 
        catch(Exception ex){
            JOptionPane.showMessageDialog(this,ex);
        }
        return null;
    }
    
    private String incrementID(String id){
        StringBuilder sb=new StringBuilder(); 
            for(int i=0;i<id.length();i++){ 
                if(i==0){
                    sb.append((char)(id.charAt(i))); 
                    continue;
                }
                sb.append((char)(id.charAt(i)+1)); 
            }
        return sb.toString();
    }
    
    private void validateBooking(){
        if (txtBModel.getText().equals(""))
            txtBookError.setText("Please select a vehicle");
        else if (!txtBnom.getText().matches("[0-9]+"))
            txtBookError.setText("Please input number of months properly");
        else if (Integer.parseInt(txtBnom.getText()) <= 0)
            txtBookError.setText("Please enter valid no of months");
        else if (!txtAdvPay.getText().matches("[0-9]+"))
            txtBookError.setText("Please input numbers only for Advance payment");
        else if (Integer.parseInt(txtAdvPay.getText()) < 0)
            txtBookError.setText("Please enter valid value for advance payment");
        else if (!txtCName.getText().matches("[a-zA-Z_]+"))
            txtBookError.setText("Please input letters only for name");
        else if (txtCAddress.getText().equals(""))
            txtBookError.setText("Please fill customer  address");
        else if (!txtCContact.getText().matches("^\\d{10}$"))
            txtBookError.setText("Please enter valid contact");
        else if (imgCustomer.getIcon()==null)
            txtBookError.setText("Please insert a customer photo");
        else{
            txtBookError.setText("");
        }
        
    }
    
    private void validateAdd(){
         if (txtLplate.getText().equals(""))
            txtAddError.setText("Please enter a vehicle number");
        else if (cmbYear.getSelectedIndex() == 0)
            txtAddError.setText("Please select a year");
        else if (cmbMake.getSelectedIndex() == 0)
            txtAddError.setText("Please select a Vehicle Make");
        else if (cmbCategory.getSelectedIndex() == 0)
            txtAddError.setText("Please Select a Vehicle Category");
        else if (txtModel.getText().equals(""))
            txtAddError.setText("Please enter a vehicle model");
        else if (txtCostpm.getText().equals(""))
            txtAddError.setText("Please enter cost per month");
        else if (Integer.parseInt(txtCostpm.getText()) <= 0)
            txtAddError.setText("Please enter valid a cost");
        else if (!txtCostpm.getText().matches("[0-9]+"))
            txtAddError.setText("Please input numbers only for cost");       
        else if (imgVehicle.getIcon()==null)
            txtAddError.setText("Please insert a Vehicle photo");
        else{
            txtAddError.setText("");
        }       
    }
    
       private void validateSearch(){
         if (cmbSPlateNo.getSelectedIndex() == -1)
            txtSearchError.setText("Please select a vehicle number");
        else if (txtSYear.getText().equals(""))
            txtSearchError.setText("Year cannot be blank");
        else if (txtSMake.getText().equals(""))
            txtSearchError.setText("Make cannot be blank");
        else if (txtSModel.getText().equals(""))
            txtSearchError.setText("Model cannot be blank");
        else if (txtSCategory.getText().equals(""))
            txtSearchError.setText("Category cannot be blank");
        else if (txtSCostPerMonth.getText().equals(""))
            txtSearchError.setText("Cost cannot be blank");
        else if (Integer.parseInt(txtSCostPerMonth.getText()) <= 0)
            txtSearchError.setText("Please enter valid a cost");
        else if (!txtSCostPerMonth.getText().matches("[0-9]+"))
            txtSearchError.setText("Please input numbers only for cost");       
        else if (imgSVehicle.getIcon()==null)
            txtSearchError.setText("Please insert a Vehicle photo");
        else{
            txtSearchError.setText("");
        }       
    }
       
    private void loadDashboard(){
        try
        {
            Connection con = DB.createConnection();
            String sql = "SELECT COUNT(LPlate) from vehicles";
            PreparedStatement ps = con.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            while(rs.next()){
                txtNOV.setText(rs.getString(1));                
            }

        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(this, "Error Loading dashboard items");
        }
        try{
            Connection con = DB.createConnection();
            String sql = "SELECT COUNT(Bk_No) from booking";
            PreparedStatement ps = con.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            while(rs.next()){
                txtNOB.setText(rs.getString(1));                
            }            
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(this, "Error Loading dashboard items");
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnAddV;
    private javax.swing.JButton btnBBrowse;
    private javax.swing.JButton btnBSearch;
    private javax.swing.JButton btnBill;
    private javax.swing.JButton btnBook;
    private javax.swing.JLabel btnBookV;
    private javax.swing.JButton btnBrowse;
    private javax.swing.JButton btnBrowseSearch;
    private javax.swing.JButton btnCalculate;
    private javax.swing.JButton btnClear;
    private javax.swing.JLabel btnClose;
    private javax.swing.JButton btnDelete;
    private javax.swing.JLabel btnHome;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel btnSearchV;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnView;
    private javax.swing.JLabel btnViewV;
    private javax.swing.JPanel buttonClose;
    private javax.swing.JComboBox<String> cmbBLplate;
    private javax.swing.JComboBox<String> cmbCategory;
    private javax.swing.JComboBox<String> cmbMake;
    private javax.swing.JComboBox<String> cmbSPlateNo;
    private javax.swing.JComboBox<String> cmbYear;
    private javax.swing.JPanel dash;
    private javax.swing.JTabbedPane dashTabPanel;
    private javax.swing.JPanel header;
    private javax.swing.JLabel imgCustomer;
    private javax.swing.JLabel imgSVehicle;
    private javax.swing.JLabel imgVehicle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel menu;
    private javax.swing.JPanel menuSlide;
    private javax.swing.JPanel meunIcons;
    private javax.swing.JPanel optionIcons;
    private javax.swing.JPanel tabAddVehicle;
    private javax.swing.JPanel tabBookVehicle;
    private javax.swing.JPanel tabHome;
    private javax.swing.JPanel tabSearchVehicle;
    private javax.swing.JPanel tabViewVehicle;
    private javax.swing.JTable tableVehicle;
    private javax.swing.JLabel txtAddError;
    private javax.swing.JTextField txtAdvPay;
    private javax.swing.JTextField txtBCostpMonth;
    private javax.swing.JTextField txtBDate;
    private javax.swing.JTextField txtBMake;
    private javax.swing.JTextField txtBModel;
    private javax.swing.JTextField txtBNo;
    private javax.swing.JTextField txtBYear;
    private javax.swing.JTextField txtBillAmt;
    private javax.swing.JTextField txtBnom;
    private javax.swing.JLabel txtBookError;
    private javax.swing.JTextArea txtCAddress;
    private javax.swing.JTextField txtCContact;
    private javax.swing.JTextField txtCName;
    private javax.swing.JTextField txtCostpm;
    private javax.swing.JTextField txtFinalBill;
    private javax.swing.JTextField txtLplate;
    private javax.swing.JTextField txtModel;
    private javax.swing.JLabel txtNOB;
    private javax.swing.JLabel txtNOV;
    private javax.swing.JTextField txtSCategory;
    private javax.swing.JTextField txtSCostPerMonth;
    private javax.swing.JTextField txtSMake;
    private javax.swing.JTextField txtSModel;
    private javax.swing.JTextField txtSYear;
    private javax.swing.JLabel txtSearchError;
    // End of variables declaration//GEN-END:variables

}
