/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.DB;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Bawantha
 */
public class PasswordRecovery extends javax.swing.JDialog {

    /**
     * Creates new form PasswordRecovery
     */
    public PasswordRecovery(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        hideLabels();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtEmail = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        lblUname = new javax.swing.JLabel();
        lblPwd = new javax.swing.JLabel();
        txtPwd = new javax.swing.JPasswordField();
        lblConfirm = new javax.swing.JLabel();
        txtConfirm = new javax.swing.JPasswordField();
        btnRecover = new javax.swing.JLabel();
        txtError = new javax.swing.JLabel();
        btnRegister = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(99, 99, 101));
        txtEmail.setPreferredSize(new java.awt.Dimension(60, 20));
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 320, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 59, 191));
        jLabel3.setText("EMAIL");
        jLabel3.setToolTipText("");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, -1, -1));

        txtUsername.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtUsername.setForeground(new java.awt.Color(99, 99, 101));
        txtUsername.setPreferredSize(new java.awt.Dimension(60, 20));
        jPanel1.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 320, 30));

        lblUname.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblUname.setForeground(new java.awt.Color(0, 59, 191));
        lblUname.setText("USERNAME");
        lblUname.setToolTipText("");
        jPanel1.add(lblUname, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, -1, -1));

        lblPwd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPwd.setForeground(new java.awt.Color(0, 59, 191));
        lblPwd.setText("NEW PASSWORD");
        lblPwd.setToolTipText("");
        jPanel1.add(lblPwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, -1, -1));

        txtPwd.setForeground(new java.awt.Color(99, 99, 101));
        txtPwd.setText("jPasswordField1");
        txtPwd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPwdFocusGained(evt);
            }
        });
        jPanel1.add(txtPwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, 320, 30));

        lblConfirm.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblConfirm.setForeground(new java.awt.Color(0, 59, 191));
        lblConfirm.setText("CONFIRM NEW PASSWORD");
        lblConfirm.setToolTipText("");
        jPanel1.add(lblConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 410, -1, -1));

        txtConfirm.setForeground(new java.awt.Color(99, 99, 101));
        txtConfirm.setText("jPasswordField2");
        txtConfirm.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtConfirmFocusGained(evt);
            }
        });
        jPanel1.add(txtConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 440, 320, 30));

        btnRecover.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnRecover.setForeground(new java.awt.Color(0, 204, 0));
        btnRecover.setText("RECOVER");
        btnRecover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRecoverMouseClicked(evt);
            }
        });
        jPanel1.add(btnRecover, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 80, 30));

        txtError.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        txtError.setForeground(new java.awt.Color(255, 0, 0));
        txtError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtError.setToolTipText("");
        jPanel1.add(txtError, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 480, 260, 30));

        btnRegister.setIcon(new javax.swing.ImageIcon("E:\\Downloads\\output-onlinepngtools.png")); // NOI18N
        btnRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegisterMouseClicked(evt);
            }
        });
        jPanel1.add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 520, -1, 70));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon("E:\\Downloads\\pure-white-background-85a2a7fd.jpg")); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 480, 570));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon("E:\\Downloads\\blue-grunge-free-vector-texture.jpg")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 667, 670));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(683, 706));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtPwdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPwdFocusGained
        txtPwd.setText("");
    }//GEN-LAST:event_txtPwdFocusGained

    private void txtConfirmFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtConfirmFocusGained
        txtConfirm.setText("");
    }//GEN-LAST:event_txtConfirmFocusGained

    private void btnRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegisterMouseClicked
        if(txtUsername.getText().equals(""))
        txtError.setText("Enter a username");
        else if (txtPwd.getText().equals(""))
        txtError.setText("Enter a password");
        else if(txtPwd.getText().equals(txtConfirm.getText())){
            try{
                Connection con = DB.createConnection();
                String sql = "Update login set username = '"+txtUsername.getText()+"' ,password = '"+txtPwd.getText()+"' where email = '"+txtEmail.getText()+"' ";
                PreparedStatement statement = con.prepareStatement(sql);
                int i = statement.executeUpdate();
                if(i==1){
                    JOptionPane.showMessageDialog(null,"Account Updated Succesfully");
                    this.setVisible(false);
                }
                else{
                    JOptionPane.showMessageDialog(null,"Could not Update ");
                }
            }
            catch(Exception e){
                System.out.println(e.getLocalizedMessage());
            }
        }
        else{
            txtError.setText("Passwords do not match");

        }
    }//GEN-LAST:event_btnRegisterMouseClicked

    private void btnRecoverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRecoverMouseClicked
            checkEmail();
            /*if(!txtUsername.getText().equals("")){
               try{
             Connection con = DB.createConnection();
             String sql = "select * from login  where username=? and password=? ";
              PreparedStatement pst = con.prepareStatement(sql);
              pst.setString(1, txtUsername.getText());
              pst.setString(2, txtPwd.getText());
              ResultSet rs = pst.executeQuery();
              if(!rs.next()){
                  JOptionPane.showMessageDialog(null, "Username and Password do not match");
                  txtPwd.setText("");
                  txtUsername.setText("");
              }
              else{
                  MainMenu mm = new MainMenu();
                  mm.setVisible(true);
                  this.setVisible(false);
              }
              con.close();
         }
         catch(Exception e){
             JOptionPane.showMessageDialog(null,e);
         }         
            }*/
            
    }//GEN-LAST:event_btnRecoverMouseClicked

    public void hideLabels(){
        lblUname.setVisible(false);
        txtUsername.setVisible(false);
        lblPwd.setVisible(false);
        txtPwd.setVisible(false);
        lblConfirm.setVisible(false);
        txtConfirm.setVisible(false);
        btnRegister.setVisible(false);
    }
    public void showLabels(){
        lblUname.setVisible(true);
        txtUsername.setVisible(true);
        lblPwd.setVisible(true);
        txtPwd.setVisible(true);
        lblConfirm.setVisible(true);
        txtConfirm.setVisible(true);
        btnRegister.setVisible(true);
    }
    public void checkEmail(){
            try{
              Connection con = DB.createConnection();
                String sql = "select * from login  where email='"+txtEmail.getText()+"'";
                PreparedStatement ps = con.prepareStatement(sql);
                ResultSet rs = ps.executeQuery();
                if(!rs.next()){
                    JOptionPane.showMessageDialog(null, "Noo such email found");
                    txtEmail.setText("");
                    hideLabels();
                }
                else{
                    txtUsername.setText(rs.getString(3));
                    showLabels();
                }
            }
            catch(Exception e){
               JOptionPane.showMessageDialog(null,e); 
            }        
    }
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PasswordRecovery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PasswordRecovery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PasswordRecovery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PasswordRecovery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PasswordRecovery dialog = new PasswordRecovery(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnRecover;
    private javax.swing.JLabel btnRegister;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblConfirm;
    private javax.swing.JLabel lblPwd;
    private javax.swing.JLabel lblUname;
    private javax.swing.JPasswordField txtConfirm;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JLabel txtError;
    private javax.swing.JPasswordField txtPwd;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
